config/routes.rb
Rails.application.routes.draw do
  get '/matches/new' => 'management#new_match', as: 'new_match'
  post '/matches/create' => 'management#create_match', as: 'create_match'
  get '/matches/list' => 'management#match_list', as: 'match_list'
  get '/matches/list/:id' => 'management#edit_match'
  post '/matches/list/:id/active' => 'management#active_match'
  post '/:account' => 'page#create_enrolment', as: 'create_enrolment'
  get '/matches/list/export/:id' => 'management#export_enrolment'
  get '/admin/:name' => 'management#manage', as: 'user_management'

  devise_for :users
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  root 'page#home'

  get '*path' => redirect('/')
end

app/models/enrolment.rb
class Enrolment < ActiveRecord::Base
  has_many :matches
  # validate account with Chinese, English and Korean
  validates :account, :presence => { :message => "canot be blank!!!"},
                      :length => { :within => 6..20, :message => "must be realistic!" },
                      :format => { with: /([A-Za-z\u4e00-\u9fa5\u2E80-\u9FFF\uac00-\ud7ff]{3,12}#\d{4,10})/, :message => "format should be like [Account#BattleTag] !!!" }
  validate :unique_enrolment_for_matches

  def unique_enrolment_for_matches
    result = Enrolment.where(account: self.account, match_id: self.match_id).first

    if result
      errors.add(:enrolment, " account has already enroled!!!")
    end
  end

  def export_enrolment(m_id)
    list = Enrolment.where(:match_id => m_id)
    output = File.open("./private/enrol_list.csv", "w")
    list.each do |item|
      output << "#{item.account}\n"
    end

    output.close
  end

  def permited_params(params)
    params.require(:enrolment).permit(:account, :match_id)
  end
end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :enrolment
  validates :name, presence: true, length: { minimum: 3, maximum: 200 }
  validates :time, presence: true, uniqueness: true
  validates :rules, presence: true, length: { minimum: 10, maximum: 500 }

  #save new match to model
  def save_match(match_params)
    self.name = match_params[:name]
    if self.time != Time.parse("#{match_params['time(1i)']}.-#{match_params['time(2i)']}-#{match_params['time(3i)']} #{match_params['time(4i)']}:#{match_params['time(5i)']}")
      self.time = Time.parse("#{match_params['time(1i)']}.-#{match_params['time(2i)']}-#{match_params['time(3i)']} #{match_params['time(4i)']}:#{match_params['time(5i)']}")
    end

    self.rules = match_params[:rules]
    self.save
  end

  def acitve
    list = Match.where(status: true)

    list.each do |item|
      item.status = false
      item.save
    end

    self.status = true
    self.save
  end

  def permited_params(params)
    params.require(:match).permit(:name, :time, :rules)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  # redirect user to their user management page after signed in
  def after_sign_in_path_for(users)
    request.env['omniauth.origin'] || stored_location_for(users) || user_management_path(current_user.name)
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/management_controller.rb
class ManagementController < ApplicationController
  before_action :check_login, only: :manage

  def manage
  end

  def new_match
    @match = Match.new
  end

  def create_match
    if match_params[:id]
      @match = Match.find(match_params[:id])
      @match.save_match(match_params)
    elsif

    @match = Match.new
    @match.save_match(match_params)
    end

    redirect_to match_list_path
  end

  def match_list
    @match_list = Match.all
  end

  def edit_match
    @match = Match.find(params[:id])
  end

  def active_match
    @match = Match.find(params[:id])
    @match.acitve

    redirect_to match_list_path
  end

  def export_enrolment
    @list = Enrolment.new
    @list.export_enrolment(params[:id])
    send_file Rails.root.join('private', 'enrol_list.csv'), :type=>"application/csv", :x_sendfile=>true
  end


  # check whether user has loged in. If users access to other user's account,
  # they will get a warning and redirect to root page.
  private
  def check_login
    redirect_to :new_user_session unless user_signed_in?

    if current_user && current_user.name != params[:name]
      flash[:notice] = "Sorry #{current_user.name}, you can't access to this account!"
      redirect_to :root
    end
  end

  def match_params
    params.require(:match).permit!
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
    @enrolment = Enrolment.new
    @match = Match.where(status: true).first
  end

  def create_enrolment
    @enrolment = Enrolment.new(:account => enrolment_params[:account], :match_id => enrolment_params[:match_id])
    @enrolment.save
    @match = Match.where(status: true).first

    # redirect_to root_path
    render "home"
  end

  def enrolment_params
    params.require(:enrolment).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/management_helper.rb
module ManagementHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div style="400px" align="center">
      <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
        <%= content_tag :div, msg %>
        <a href="#" class="close">&times;</a>
      </div>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
      <li class="name"><%= link_to 'Home', root_path %></li>
  </ul>

  <div class="top-bar-section">
    <ul class="right">
      <% if current_user %>
      <li class="has-dropdown">
        <a href="#">Profile Settings</a>
        <ul class="dropdown">
          <li><%= link_to "Edit Profile", edit_user_registration_path, method: :get %></li>
          <li class="active"><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        </ul>
      </li>
      <% else %>
      <li class="active"><%= link_to "Sign In", new_user_session_path, method: :get %></li>
      <% end %>
    </ul>

    <ul class="left">
      <% if current_user %>
      <li><%= link_to "#{current_user.name}", user_management_path(current_user.name), method: :get %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/_sidebars.html.erb
<ul class="side-nav">
  <li><%= link_to "Create New Match", new_match_path %></li>
  <li class="divider"></li>
  <li><%= link_to "Show Match List", match_list_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Hearthstone Forum" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Hearthstone Forum" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <% if current_user %>
      <main role="main">
        <div class="row">
          <div class="small-3 columns">
            <%= render 'layouts/sidebars' %>
          </div>
          <div class="small-9 columns">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
      </main>
    <% elsif %>
      <main role="main">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </main>
    <% end %>
  </body>
</html>

app/views/management/_form.html.erb
<%= form_for @match, url: create_match_path, method: :post, :html => { :multipart => true } do |f| %>
<%= f.hidden_field :lock_version %>
<% if @match.id %>
<%= f.hidden_field :id %>
<% end %>
<p>
  <%= f.label :name, "Match Name" %>
  <%= f.text_field :name %>
</p>
<p>
  <%= f.label :time, "Match Start Time" %>
  <%= f.datetime_select :time, :ampm => true, :minute_step => 15%>
</p>
<p>
  <%= f.label :rules, "Match Rules" %>
  <%= f.text_area :rules %>
</p>
<p>
  <%= f.button "Submit" %> &nbsp;&nbsp;&nbsp;
  <%= link_to 'Back', { :controller => 'management', :action => 'match_list'}, class:'button'%>
</p>
<% end %>

app/views/management/edit_match.html.erb
<h1>Edit Match Page<h1>
<%= render 'form' %>

app/views/management/manage.html.erb
<h1>Hello <%= current_user.name %></h1>

app/views/management/match_list.html.erb
<h1>Match List</h1>
<table>
<tr>
  <th>Match Name</th>
  <th>Time</th>
  <th>Create Time</th>
  <th>Options</th>
  <th>Active</th>
  <th>Download List</th>
</tr>

<% @match_list.each do |item| %>
<tr>
  <td><%= item.name %></td>
  <td><%= item.time %></td>
  <td><%= item.created_at %></td>
  <td><%= link_to "Edit", controller: "management", action: "edit_match", id: item.id %></td>
  <td><%= button_to "Active",{ :controller=> "management", :action=> "active_match", :id => item.id}, class:'button tiny success' %></td>
  <td><%= link_to "List", controller: "management", action: "export_enrolment", id: item.id %></td>
</tr>
<% end %>
</table>

app/views/management/new_match.html.erb
<h1>New Match Page<h1>
<%= render 'form' %>

app/views/page/home.html.erb
<style>
  #confirmBtn input {
    width:650px;
  }
</style>
<div align="center">
<div align="left" style="width: 650px">
  <div>
    <h2 style="color: #563d7c">Hearthstone Public Match Enrolment</h2>
  </div>
  </br>
  <h3 style="color: #8a8a8a">Match Information</h3>
  <table width="650px">
  <tr>
    <th>Match Name</th>
    <th>Time</th>
    <th>Rules</th>
  </tr>

  <% if @match %>
  <tr>
    <td><%= @match.name %></td>
    <td><%= @match.time %></td>
    <td><%= @match.rules %></td>
  </tr>
  </table>

  <div>
    <%= form_for @enrolment, url: create_enrolment_path(:account), method: :post do |f| %>
    <% if @enrolment.errors.any? %>
      <div id="error_explanation">
        <% @enrolment.errors.full_messages.each do |msg| %>
          <div data-alert class="alert-box warning round">
            <%= content_tag :div, msg %>
            <a href="#" class="close">&times;</a>
          </div>
        <% end %>
      </div>
    <% end %>

    <%= f.hidden_field :match_id, :value => @match.id %>
    <%= f.label :account, "Account#BattleTag" %>
    <div id="confirmBtn">
       <%= f.text_field :account %>
    </div>
    <%= f.button "Submit" %>&nbsp;&nbsp;&nbsp;
    <input type="reset" class="button disabled" value="reset"/>
    <% end %>
  </div>
  <% end %>
</div>
</div>